functions:
  actions:
    lang: golang-middleware
    handler: ./src/controllers/actions
    image: qolzam/actions:v0.4
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /actions
      cookie_root_domain: .o6s.io
      db_type: mongo
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/action_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  admin:
    lang: golang-middleware
    handler: ./src/controllers/admin
    image: qolzam/admin:v0.21
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /admin
      cookie_root_domain: .o6s.io
      db_type: mongo
      exec_timeout: "20"
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/admin_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  auth:
    lang: golang-middleware
    handler: ./src/controllers/users/auth
    image: qolzam/auth:v0.17
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /auth
      client_id: 7a9cbbf3e0bce602784f
      client_secret: ""
      cookie_root_domain: .o6s.io
      db_type: mongo
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      github_app_id: "12345"
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      oauth_client_secret_path: /var/openfaas/secrets/ts-client-secret
      oauth_provider: github
      oauth_provider_base_url: ""
      oauth_telar_base_url: ""
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      report_status: "true"
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      verify_type: emv
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/auth_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: auth-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  notifications:
    lang: golang-middleware
    handler: ./src/controllers/notifications
    image: qolzam/notifications:v0.2
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /notifications
      cookie_root_domain: .o6s.io
      db_type: mongo
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/notification_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  profile:
    lang: golang-middleware
    handler: ./src/controllers/users/profile
    image: qolzam/profile:v0.2
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /profile
      cookie_root_domain: .o6s.io
      db_type: mongo
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/profile_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  setting:
    lang: golang-middleware
    handler: ./src/controllers/users/setting
    image: qolzam/setting:v0.2
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /setting
      cookie_root_domain: .o6s.io
      db_type: mongo
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/setting_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
  storage:
    lang: golang-middleware
    handler: ./src/controllers/storage
    image: qolzam/storage:v0.2
    fprocess: ""
    environment:
      app_name: Telar Social
      base_route: /storage
      bucket_name: resume-web-app.appspot.com
      cookie_root_domain: .o6s.io
      db_type: mongo
      exec_timeout: "20"
      external_domain: https://red-gold.o6s.io
      external_redirect_domain: https://red-gold.o6s.io/auth
      gateway: https://red-gold.o6s.io
      header_cookie_name: he
      mongo_database: test
      mongo_host: mongodb+srv://telar_user:%s@cluster0-l6ojz.mongodb.net/test?retryWrites=true&w=majority
      mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
      mongo_user: telar_user
      org_avatar: https://avatars3.githubusercontent.com/u/43268620
      org_name: Red Gold
      origin: https://red-gold.o6s.io
      payload_cookie_name: pa
      phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
      phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
      phone_source_number: "0123456"
      private_key_path: /var/openfaas/secrets/key
      public_key_path: /var/openfaas/secrets/key.pub
      query_pretty_url: "true"
      read_timeout: 10s
      recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
      recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
      redis_address: redis-19712.c12.us-east-1-4.ec2.cloud.redislabs.com:19712
      ref_email: polling.social@gmail.com
      ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
      signature_cookie_name: si
      smtp_email: smtp.gmail.com
      storage_secret_path: /var/openfaas/secrets/serviceAccountKey.json
      web_domain: https://red-gold.o6s.io
      websocket_server_url: https://red-gold-socket.herokuapp.com
      write_debug: "true"
      write_timeout: 10s
    secrets:
    - secrets
    skip_build: false
    constraints: null
    environment_file:
    - config/app_config.yml
    - config/storage_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
    limits: null
    requests: null
    readonly_root_filesystem: false
    build_options: []
    annotations:
      linkerd.io/inject: disabled
provider:
  name: faas
  gateway: http://127.0.0.1:8080
  network: ""
