environment:
  base_route: /auth
  client_id: 7a9cbbf3e0bce602784f
  client_secret: ""
  github_app_id: "12345"
  oauth_client_secret_path: /var/openfaas/secrets/ts-client-secret
  oauth_provider: github
  oauth_provider_base_url: ""
  oauth_telar_base_url: ""
  report_status: "true"
  verify_type: emv
  write_debug: "true"
